[workspace]
members = [
    'discord-bot',
    'blockchain/node',
    'blockchain/runtime',
    'pallet-discord',

    # Remove these later
    "subxt", "subxt/cli", "subxt/codegen", "subxt/macro"
]

[profile.release]
panic = 'unwind'